project_id = "ktlbseweighlrhoxbjii"

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-speech]
verify_jwt = true

[functions.send-push-notifications]
verify_jwt = false

[functions.realtime-transcribe]
verify_jwt = true

[functions.analyze-presentation]
verify_jwt = true

[functions.whisper-stream]
verify_jwt = true