project_id = "ktlbseweighlrhoxbjii"

[functions.transcribe-audio]
verify_jwt = true

[functions.analyze-speech]
verify_jwt = true

[functions.send-push-notifications]
verify_jwt = false

[functions.realtime-transcribe]
verify_jwt = true

[functions.analyze-presentation]
verify_jwt = true

[functions.whisper-stream]
verify_jwt = true

[functions.realtime-speech-training]
verify_jwt = false

[functions.analyze-freestyle-speech]
verify_jwt = true

[functions.analyze-freestyle-session]
verify_jwt = true

[functions.update-sm2-schedule]
verify_jwt = true

[functions.update-adaptive-learning]
verify_jwt = true

[functions.update-adaptive-word-hiding]
verify_jwt = true

[functions.segment-speech]
verify_jwt = false

[functions.send-adaptive-notifications]
verify_jwt = false

[functions.update-segment-word-mastery]
verify_jwt = true

[functions.segment-speech-into-beats]
verify_jwt = false
